name = "planning-poker-online"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_date = "2024-06-16"
compatibility_flags = ["nodejs_compat"]

# Uncomment and configure if using KV, D1, or other bindings
# [[kv_namespaces]]
# binding = "MY_KV"
# id = "your-kv-namespace-id"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = "your-database-id"

# Environment variables (add as needed)
# [vars]
# PUBLIC_API_URL = "https://api.example.com"